include: package:lint/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "lib/generated/**"
    - "lib/generated_*"
    - "lib/proto/**"
    - "lib/i18n/messages_*.dart"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.graphql.dart"
    - "**/*.gql.dart"